services:
  postgres:
    image: postgres:16
    container_name: tasks-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: userzinho
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tasksdb

    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
